interface user {
    email: String,
    password: String,
    role: String,
    firstname: String,
    lastname: String,
    status: String,
    reviews: review[],
    is_deleted: Boolean,
    is_active: Boolean,
    deleted_by: String,
    deletion_time: String,
    creation_time: String,
    updated_by: String,
    updation_time: String,
}